### ISSUE TITLE
buttons bug

### ISSUE THREAD

**Issue by gquintela** [gquintela/calculator#1]
https://github.com/gquintela/calculator/blob/657f950e55b9622bf287072594dcc906aeb11c79/code.js#L212-L225

When clicking "acum button" after clicking the "normal button" the following error is shown:

<code> Uncaught TypeError: acum_mode is not a function
    at HTMLDivElement.<anonymous> (code.js:117)</code>

**Comment by guillermoparral1995** [comment]
El problema está en que tenés una variable y una función con el mismo nombre, fijate de cambiar eso

**Comment by gquintela** [comment]
Corregido!
